// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0x_N_V3Mw34PpSQs_9kpqXh2MSLkF_ZU',
    appId: '1:379880911609:web:c3c61b1c8a1e797f60a828',
    messagingSenderId: '379880911609',
    projectId: 'movie-assistant-a2ba0',
    authDomain: 'movie-assistant-a2ba0.firebaseapp.com',
    databaseURL: 'https://movie-assistant-a2ba0-default-rtdb.firebaseio.com',
    storageBucket: 'movie-assistant-a2ba0.appspot.com',
    measurementId: 'G-BZR4YYH8V6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOx3mGgK9L8g7hMGWJdx5oAJEQJrJL9k4',
    appId: '1:379880911609:android:74b891137036a54f60a828',
    messagingSenderId: '379880911609',
    projectId: 'movie-assistant-a2ba0',
    databaseURL: 'https://movie-assistant-a2ba0-default-rtdb.firebaseio.com',
    storageBucket: 'movie-assistant-a2ba0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3RFLEC7hxJTeqwZnvlQMshXiuoH92k_c',
    appId: '1:379880911609:ios:7bcbf58488565e7c60a828',
    messagingSenderId: '379880911609',
    projectId: 'movie-assistant-a2ba0',
    databaseURL: 'https://movie-assistant-a2ba0-default-rtdb.firebaseio.com',
    storageBucket: 'movie-assistant-a2ba0.appspot.com',
    iosClientId: '379880911609-pnrv48cb5pkqfvnk434sis4irqn16oi0.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3RFLEC7hxJTeqwZnvlQMshXiuoH92k_c',
    appId: '1:379880911609:ios:7bcbf58488565e7c60a828',
    messagingSenderId: '379880911609',
    projectId: 'movie-assistant-a2ba0',
    databaseURL: 'https://movie-assistant-a2ba0-default-rtdb.firebaseio.com',
    storageBucket: 'movie-assistant-a2ba0.appspot.com',
    iosClientId: '379880911609-pnrv48cb5pkqfvnk434sis4irqn16oi0.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0x_N_V3Mw34PpSQs_9kpqXh2MSLkF_ZU',
    appId: '1:379880911609:web:f812bdf0b9d58adc60a828',
    messagingSenderId: '379880911609',
    projectId: 'movie-assistant-a2ba0',
    authDomain: 'movie-assistant-a2ba0.firebaseapp.com',
    databaseURL: 'https://movie-assistant-a2ba0-default-rtdb.firebaseio.com',
    storageBucket: 'movie-assistant-a2ba0.appspot.com',
    measurementId: 'G-J0RBNJ7EHZ',
  );
}
